name: Publish Docker image and Deploy to Minikube

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: shantanu99/ss_pro1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_to_minikube:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Set up Minikube
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget apt-transport-https
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.30.0/minikube-linux-amd64
          sudo chmod +x minikube
          sudo mv minikube /usr/local/bin/
      
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Set up kubectl for Minikube
        run: |
          alias kubectl='minikube kubectl --'
          kubectl version --client

      - name: Log in to Docker Hub (for Minikube)
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull Docker image to Minikube
        run: |
          kubectl create deployment ss_pro1 --image=shantanu99/ss_pro1:${{ steps.meta.outputs.tags }}
          kubectl expose deployment ss_pro1 --type=LoadBalancer --port=8080
          kubectl rollout status deployment/ss_pro1

      - name: Test the deployment
        run: |
          minikube service ss_pro1 --url
